### ISSUE TITLE
Calendars Menu is blank

### ISSUE THREAD

**Issue by alexthemitchell** [GrinnellAppDev/Grinnell-Events-iOS#21]
# Problem
In the settings menu, there is a "Calendar" option. Clicking this option asks for permission to see your calendars, but then shows nothing.

# Details
* Conflicts still appear normally in the event details section

![simulator screen shot nov 21 2016 11 36 03 am](https://cloud.githubusercontent.com/assets/5687158/20493537/e3f23172-afde-11e6-8241-32760d3581d9.png)
![simulator screen shot nov 21 2016 11 36 05 am](https://cloud.githubusercontent.com/assets/5687158/20493538/e3f765e8-afde-11e6-97de-5c8d9050c4bb.png)

**Comment by alexthemitchell** [comment]
Some relevant log output:
```
2016-11-21 11:35:59.867 Grinnell-Events[65989:2438200] Error getting all calendars: Error Domain=EKCADErrorDomain Code=1014 "(null)"
2016-11-21 11:35:59.871 Grinnell-Events[65989:2438200] Error getting default calendar for new events: Error Domain=EKCADErrorDomain Code=1014 "(null)"
```

**Comment by frenchal17** [comment]
![img_1630](https://cloud.githubusercontent.com/assets/7132954/20499213/154698f0-aff6-11e6-9b6a-eacd1d2b3e18.PNG)
This is what it appears to look like on the AppStore currently. What exactly is this part of that app supposed to do, and is it possible that the fact that it's running on a simulator is what is causing the problem?

**Comment by alexthemitchell** [comment]
@frenchal17 That's a good point! I just checked in the beta version and it shows the iPhone's calendars correctly. Sorry for the noise.
